"""Adding Final shop model

Revision ID: 0d7daed98b23
Revises: cafd2ee30a64
Create Date: 2024-08-13 01:00:52.477560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7daed98b23'
down_revision = '33ef0771402f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_bird_id_fkey', 'shop', type_='foreignkey')
    op.create_foreign_key(None, 'shop', 'birds', ['bird_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_foreign_key('shop_bird_id_fkey', 'shop', 'birds', ['bird_id'], ['id'])
    # ### end Alembic commands ###
