"""Initial migration2

Revision ID: 33ef0771402f
Revises: 4f99cee927df
Create Date: 2024-08-05 18:30:10.014687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ef0771402f'
down_revision = '4f99cee927df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('image_id', sa.String(), nullable=False))
    op.alter_column('shop', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(asdecimal=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'price',
               existing_type=sa.Float(asdecimal=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('birds', 'image_id')
    # ### end Alembic commands ###
