"""Initial migration

Revision ID: 4f99cee927df
Revises: 
Create Date: 2024-08-04 00:52:58.281960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f99cee927df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_bird', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cross_or_breed', sa.String(), nullable=False),
    sa.Column('meat_egg_complex', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    op.drop_table('birds')
    # ### end Alembic commands ###
