"""Initial migration

Revision ID: f440567734cb
Revises: 
Create Date: 2024-09-29 22:14:10.450576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f440567734cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_of_bird', sa.String(), nullable=False),
    sa.Column('cross_or_breed', sa.String(), nullable=True),
    sa.Column('meat_egg_complex', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(asdecimal=True), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    op.drop_table('birds')
    # ### end Alembic commands ###
